// import type { H3Event } from 'h3'
import { generateImage } from '~~/server/domains/repositories/image'
import { kv } from '@vercel/kv'

export default defineEventHandler(async (event) => {
  // レート制限チェック（一日5回まで）
  const clientIP = getHeader(event, 'x-forwarded-for') || getHeader(event, 'x-real-ip') || 'unknown'
  const today = new Date().toISOString().split('T')[0] // YYYY-MM-DD形式
  const rateLimitKey = `daily_limit:${clientIP}:${today}`

  try {
    const currentCount = (await kv.get(rateLimitKey) as number) || 0

    if (currentCount >= 5) {
      throw createError({
        statusCode: 429,
        statusMessage: '1日の使用回数制限（5回）に達しました。時間をおいてから再度お試しください。',
      })
    }
    const body = await readBody<{ prompt: string, latLng: google.maps.MapMouseEvent['latLng'] }>(event)

    // プロンプトの基本検証
    if (!body.prompt || body.prompt.trim().length < 3 || body.prompt.trim().length > 200) {
      throw createError({
        statusCode: 400,
        statusMessage: 'プロンプトは3文字以上200文字以下で入力してください',
      })
    }

    const result = await generateImage(body)

    // 成功時にカウントを増加（24時間で期限切れ）
    await kv.setex(rateLimitKey, 86400, currentCount + 1)

    console.log(result, 'result')
    return result
  }
  catch (error: any) {
    // レート制限エラーはそのまま投げる
    if (error.statusCode === 429 || error.statusCode === 400) {
      throw error
    }

    console.error('画像生成エラー:', error)
    throw createError({
      statusCode: 500,
      statusMessage: '画像生成に失敗しました。しばらく待ってから再試行してください。',
    })
  }
  // return new Promise((resolve) => {
  //   setTimeout(() => {
  //     resolve({
  //       data: 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAJDklEQVR4nO3dIW5bWRSA4XmVkbFxdlBiNlJxtmBcybiLCW5U7H2MVGApxDsIDg70mz34ur2y/u/jZ+6pprL+HvL++QcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPhTltkLAI/reDyuI/Ovr6/3WmWKdV39hvKwvsxeAAD4+wQAAAQJAAAIEgAAECQAACBIAABAkAAAgCABAABBAgAAggQAAAQJAAAIEgAAECQAACBIAABAkAAAgCDfsoYHtizLOvP96/U68/npvnwZ+zfUuq5+g5nGBQAAggQAAAQJAAAIEgAAECQAACBIAABAkAAAgCABAABBAgAAggQAAAQJAAAIEgAAECQAACBIAABAkAAAgKDN7AVgpuPxuI7Mv76+3muVm1yv16nvz3a5XIbmz2/nO20Cj8cFAACCBAAABAkAAAgSAAAQJAAAIEgAAECQAACAIAEAAEECAACCBAAABAkAAAgSAAAQJAAAIEgAAECQAACAoGX2ArQty7LOfP96vc58/uFdLpeh+fPb+U6bzHH8fhyaX9fVbzDTuAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABDkW9QMWZZlHZm/Xq/3WiXpcrkMzZ/fznfa5DEdvx+H5td19RvKw3IBAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgaDN7AdpGv2c/6uvXr0Pzo/uf385D87Mdvx+H5n/++jn1/XVdl6H/ADwwFwAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAII2sxeAmS6Xy9D8+e18p00e089fP2evANzIBQAAggQAAAQJAAAIEgAAECQAACBIAABAkAAAgCABAABBAgAAggQAAAQJAAAIEgAAECQAACBIAABAkAAAgKDN7AWA2/3+7/fQ/L/f/r3TJrcZ3f90Og3NHw6HdWR+XddlaAGYyAUAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAICgzewFoOz3f7+H5vf7/dT3Rz0/P099/3Q6Dc0fDod1ZH5d12VoARjgAgAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQNBm9gIw4vPzc2h+u93eaZPHtN/vZ68wVf3/P20uAAAQJAAAIEgAAECQAACAIAEAAEECAACCBAAABAkAAAgSAAAQJAAAIEgAAECQAACAIAEAAEECAACCBAAABG1mLwAj3t7ehua/fft2p02adrvd1Pe32+3U9+GRuQAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABC0mb0AbS8vL0PzP378uNMmj2m32w3NPz093WmT23x8fEx9H8pcAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACNrMXoC25+fnofmXl5c7bTLH6J//6enpTpsANS4AABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAEbWYvQNvo9+z3+/2dNrnNbrcbmh/d/+PjY2ge6HIBAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgaDN7ARix3++nvr/b7aa+D3ArFwAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAII2sxcAbvf+/j57ham22+3sFeBhuQAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABC0mb0AjHh/f5/6/m63m/p+3efn5+wV4GG5AABAkAAAgCABAABBAgAAggQAAAQJAAAIEgAAECQAACBIAABAkAAAgCABAABBAgAAggQAAAQJAAAIEgAAELSZvQBt7+/vs1cg7HA4DM2v67rcaRX461wAACBIAABAkAAAgCABAABBAgAAggQAAAQJAAAIEgAAECQAACBIAABAkAAAgCABAABBAgAAggQAAAQJAAAI2sxegMc2+j30w+GwjsyfTqeRcSY7HA5T3x/9+wuPzAUAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAgAQAAQQIAAIIEAAAECQAACBIAABAkAAAgSAAAQJAAAIAg38LmoS3Lss7egdut6+o3CCZxAQCAIAEAAEECAACCBAAABAkAAAgSAAAQJAAAIEgAAECQAACAIAEAAEECAACCBAAABAkAAAgSAAAQJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4o/4Hd8GaZhRfRogAAAAASUVORK5CYII=',
  //       mimeType: 'image/png',
  //       type: 'image',
  //     })
  //   }, 2000)
  // })
})
